/**
 * webapi.js 封装app所需的所有web请求
 * 供app测试使用，app加入网站后webpai应该由网站通过config,提供给每个app
 */


import { fetch } from 'edf-utils'

export default {
	vattaxpayer: {
		save: (option) => fetch.post('/v1/tax/zzssb/smallVat/save', option),
		submit: (option) => fetch.post('/v1/tax/zzssb/smallVat/submit', option),
		// smallVatInit: ( option ) => fetch.post('/v1/tax/zzssb/smallVat/init', option ),
		smallVatInit: (option) => {
			return {
				"currentDate": "2019-02-25",
				"state": 0,
				"isDeclare": false,
				"isInit": false,
				"isCanModify": false,
				"tName": "zzssyyxgmnsr",
				"isSelfemployed": false,
				"tFormulaList": [
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_qtmsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_qtmsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ynsehj=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynse)-(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynsejze)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ynsehj=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynse)-(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynsejze)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqybtse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ynsehj)-(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqyjse1)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqybtse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ynsehj)-(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqyjse1)",
					"zzsxgmflzl_flzlForm_qmye=(zzsxgmflzl_flzlForm_qcye)+(zzsxgmflzl_flzlForm_bqfse)-(zzsxgmflzl_flzlForm_bqkce)",
					"zzsxgmflzl_flzlForm_ysfwxsbqkce=(zzsxgmflzl_flzlForm_bqkce)",
					"zzsxgmflzl_flzlForm_ysfwxshsxse=(zzsxgmflzl_flzlForm_ysfwxsqbhssr)-(zzsxgmflzl_flzlForm_ysfwxsbqkce)",
					"zzsxgmflzl_flzlForm_ysfwxsbhsxse=((zzsxgmflzl_flzlForm_ysfwxshsxse)/1.03)",
					"zzsxgmflzl_flzlForm_qmye5=(zzsxgmflzl_flzlForm_qcye5)+(zzsxgmflzl_flzlForm_bqfse5)-(zzsxgmflzl_flzlForm_bqkce5)",
					"zzsxgmflzl_flzlForm_ysfwxsbqkce5=(zzsxgmflzl_flzlForm_bqkce5)",
					"zzsxgmflzl_flzlForm_ysfwxshsxse5=(zzsxgmflzl_flzlForm_ysfwxsqbhssr5)-(zzsxgmflzl_flzlForm_ysfwxsbqkce5)",
					"zzsxgmflzl_flzlForm_ysfwxsbhsxse5=((zzsxgmflzl_flzlForm_ysfwxshsxse5)/1.05)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynse=([(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)*0.03])+([(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)*0.03])",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqmse=([(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)*0.03])",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymse=([(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymsxse)*0.03])",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse=(zzsxgmflzl_flzlForm_ysfwxsbhsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse=(zzsxgmflzl_flzlForm_ysfwxsbhsxse5)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqmse=([(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)*0.03])",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymse=([(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse)*0.03])",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_xsczbdcbhsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_xsczbdcbhsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_swjgdkdzzszyfpbhsxse1=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse1)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_swjgdkdzzszyfpbhsxse1)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_skqjkjdptfpbhsxse2=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse2)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_skqjkjdptfpbhsxse2)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_xssygdysgdzcbhsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_xssygdysgdzcbhsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_skqjkjdptfpbhsxse1=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpbhsxse1)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_skqjkjdptfpbhsxse1)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_msxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_msxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_msxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_msxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_xwqymsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_xwqymsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_xwqymsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_xwqymsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_wdqzdxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_wdqzdxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_wdqzdxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_wdqzdxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_qtmsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_qtmsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_qtmsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_qtmsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_qtmsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_qtmsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_ckmsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_ckmsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_ckmsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_ckmsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_skqjkjdptfpxse1=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpxse1)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_skqjkjdptfpxse1)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_skqjkjdptfpxse1=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpxse1)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_skqjkjdptfpxse1)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqynse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqynse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqynse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqynse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqynsejze=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynsejze)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqynsejze)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqynsejze=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynsejze)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqynsejze)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqmse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqmse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqmse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqmse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqmse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqmse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_xwqymse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_xwqymse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_xwqymse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_xwqymse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_wdqzdmse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdmse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_wdqzdmse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_wdqzdmse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdmse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_wdqzdmse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_ynsehj=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ynsehj)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_ynsehj)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_ynsehj=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ynsehj)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_ynsehj)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqyjse1=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqyjse1)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqyjse1)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqyjse1=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqyjse1)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqyjse1)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqybtse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqybtse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_bqybtse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqybtse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqybtse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_bqybtse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_yzzzsbhsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_yzzzsbhsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_yzzzsbhsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_yzzzsbhsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_swjgdkdzzszyfpbhsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_swjgdkdzzszyfpbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_swjgdkdzzszyfpbhsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_swjgdkdzzszyfpbhsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_swjgdkdzzszyfpbhsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_skqjkjdptfpbhsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_2_skqjkjdptfpbhsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_skqjkjdptfpbhsxse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_3_skqjkjdptfpbhsxse)",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynse=([(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)*0.03])+([(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)*0.05])",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdmse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdxse)*0.03",
					"zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdmse=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse)*0.03"
				],
				"qtxx": {
					"xgmnsrBz": null,
					"ssqkdys": 3,
					"qzd": null,
					"myqzd": 100000,
					"yqsbBz": "Y",
					"yqsbMes": "该纳税人本属期逾期申报（逾期天数31）",
					"zzsqzd": "90000.03",
					"zzsysfwqzd": "0.0",
					"yshwlwBz": "Y",
					"ysfwBz": "N",
					"yshwlwFpdkbhsxse": "50912.63",
					"ysfwFpdkbhsxse": "0.0",
					"ysfwFpdkbhsxse5": "0.0",
					"dqdeBz": "N",
					"dqdeYshwlwHdxse": "0.0",
					"dqdeYsfwHdxse": "0.0",
					"dqdeYshwlwHdynse": "0.0",
					"dqdeYsfwHdynse": "0.0",
					"zfjgBz": "2",
					"yzl": "0.0",
					"desl1": "0.0",
					"fgdqyBz": "N",
					"fzjgfgdqyse": "0.0",
					"ysfwydbyhyyjse": "0.0",
					"hwlwydbyhyyjse": "0.0",
					"flzlqcye": "0.0",
					"flzlqcye5": "0.0",
					"qmsezzsskxtfy5": "0.0",
					"qmsefzjgyzjnsk5": "0.0",
					"qmsejzfwyzjnsk5": "0.0",
					"qmsexsbdcyzjnsk5": "0.0",
					"qmseczbdcyzjnsk5": "0.0",
					"yqwrdzzsybnsrBz": "N",
					"sqwsbmsg": null,
					"ptfpsjkpje": "0.0",
					"zpje": "50912.63",
					"ppje": "0.0",
					"iswkjfpsqd": "N",
					"fqmsqBz": "Y",
					"zgslhl": "0.0",
					"zgslfw": "0.0",
					"acsbxseHj": "0.0",
					"acsbfwxseHj": "0.0",
					"bsrxm": "李正青",
					"cwfzrxm": "李明琦",
					"fddbrxm": "徐永波",
					"bsrlxdh": "18085018512",
					"nullUpdate": {
						"$class": "boolean",
						"$": false
					},
					"ignoreTs": {
						"$class": "boolean",
						"$": false
					},
					"validateThrowException": {
						"$class": "boolean",
						"$": false
					},
					"valid": {
						"$class": "boolean",
						"$": false
					},
					"innerDto": null
				},
				"checkList": [
					{
						"id": 100010001,
						"code": "BDA0610611_10001",
						"message": "[货物及劳务]不能为负！",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010002,
						"code": "BDA0610611_10002",
						"vatTaxPayer": 2000010002,
						"message": "第1列第1栏应大于等于第2栏+第3栏之和",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)<((zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_swjgdkdzzszyfpbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpbhsxse))",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_swjgdkdzzszyfpbhsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010006,
						"code": "BDA0610611_10006",
						"vatTaxPayer": 2000010002,
						"message": "未达到起征点，不能填报第3栏第1列",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)<=30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpbhsxse)!=0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010007,
						"code": "BDA0610611_10007",
						"vatTaxPayer": 2000010002,
						"message": "第7栏必须大于等于第8栏",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)<(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpbhsxse1)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpbhsxse1",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010008,
						"code": "BDA0610611_10008",
						"vatTaxPayer": 2000010002,
						"message": "未达到起征点，不能填报第7栏第1列[销售使用过的固定资产不含税销售额]本期数",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)<=30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)!=0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010009,
						"code": "BDA0610611_10009",
						"vatTaxPayer": 2000010002,
						"message": "[货物及劳务]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010010,
						"code": "BDA0610611_10010",
						"vatTaxPayer": 2000010002,
						"message": "[货物及劳务]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010011,
						"code": "BDA0610611_10011",
						"vatTaxPayer": 2000010002,
						"message": "已达起征点，不能填报第11栏第1列[未达起征点销售额]",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)>30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdxse)!=0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010012,
						"code": "BDA0610611_10012",
						"vatTaxPayer": 2000010002,
						"message": "[货物及劳务]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_qtmsxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_qtmsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010013,
						"code": "BDA0610611_10013",
						"vatTaxPayer": 2000010002,
						"message": "主表第12栏第1列[货物及劳务]+第2列[服务、不动产和无形资产]本期数应等于附表《减免税申报明细表》第1列[免征增值税项目销售额]的合计",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_qtmsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_qtmsxse)!=(zzsjmssbmxb_zzsjmssbmxbmsxmGrid_zzsjmssbmxbmsxmGridlbVO_0_mzzzsxmxse)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_qtmsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_qtmsxse,zzsjmssbmxb_zzsjmssbmxbmsxmGrid_zzsjmssbmxbmsxmGridlbVO_0_mzzzsxmxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010014,
						"code": "BDA0610611_10014",
						"vatTaxPayer": 2000010002,
						"message": "第13栏必须大于等于第14栏",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)<(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpxse1)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpxse1",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010015,
						"code": "BDA0610611_10015",
						"vatTaxPayer": 2000010002,
						"message": "[货物及劳务]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010016,
						"code": "BDA0610611_10016",
						"vatTaxPayer": 2000010002,
						"message": "[货物及劳务]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpxse1)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_skqjkjdptfpxse1",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010023,
						"code": "BDA0610611_10023",
						"vatTaxPayer": 2000010002,
						"message": "第17行第1列+2列应等于第18行第1列+2列【数值】+第19行1列+第2列+《增值税减免税申报明细表》中免税项目免税额合计",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqmse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqmse) !=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdmse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdmse)+(zzsjmssbmxb_zzsjmssbmxbmsxmGrid_zzsjmssbmxbmsxmGridlbVO_0_mse)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqmse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqmse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdmse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdmse,zzsjmssbmxb_zzsjmssbmxbmsxmGrid_zzsjmssbmxbmsxmGridlbVO_0_mse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010024,
						"code": "BDA0610611_10024",
						"message": "第18行第1列与第19行第1列不能同时大于0",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymse)>0&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdmse)>0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_wdqzdmse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010026,
						"code": "BDA0610611_10026",
						"vatTaxPayer": 2000010002,
						"message": "本期预缴税额不能为负数",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqyjse1)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqyjse1",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010028,
						"code": "BDA0610611_10028",
						"vatTaxPayer": 2000010002,
						"message": "第3栏[本期扣除额]应小于或等于第1栏[期初余额]+第2栏[本期发生额]且第3栏[本期扣除额]应小于等于第5栏[全部含税收入]",
						"formula": "(zzsxgmflzl_flzlForm_bqkce)>(zzsxgmflzl_flzlForm_qcye)+(zzsxgmflzl_flzlForm_bqfse)|| (zzsxgmflzl_flzlForm_bqkce) > (zzsxgmflzl_flzlForm_ysfwxsqbhssr)",
						"targetName": "zzsxgmflzl_flzlForm_bqkce",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010029,
						"code": "BDA0610611_10029",
						"vatTaxPayer": 2000010002,
						"message": "第4栏[期末余额]等于第1栏[期初余额]+第2栏[本期发生额]-第3栏[本期扣除额]",
						"formula": "(zzsxgmflzl_flzlForm_qmye)!=(zzsxgmflzl_flzlForm_qcye)+(zzsxgmflzl_flzlForm_bqfse)-(zzsxgmflzl_flzlForm_bqkce)",
						"targetName": "zzsxgmflzl_flzlForm_qmye",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010030,
						"code": "BDA0610611_10030",
						"vatTaxPayer": 2000010002,
						"message": "第6栏[本期扣除额]=第3栏[本期扣除额]",
						"formula": "(zzsxgmflzl_flzlForm_ysfwxsbqkce)!=(zzsxgmflzl_flzlForm_bqkce)",
						"targetName": "zzsxgmflzl_flzlForm_ysfwxsbqkce",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010031,
						"code": "BDA0610611_10031",
						"vatTaxPayer": 2000010002,
						"message": "第7栏[含税销售额]=第5栏[全部含税收入]-第6栏[本期扣除额]",
						"formula": "(zzsxgmflzl_flzlForm_ysfwxshsxse)!=(zzsxgmflzl_flzlForm_ysfwxsqbhssr)-(zzsxgmflzl_flzlForm_ysfwxsbqkce)",
						"targetName": "zzsxgmflzl_flzlForm_ysfwxshsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010033,
						"code": "BDA0610611_10033",
						"vatTaxPayer": 2000010002,
						"message": "第11栏[本期扣除额]应小于或等于第9栏[期初余额]+第10栏[本期发生额]且第11栏[本期扣除额]应小于等于第13栏[全部含税收入]",
						"formula": "(zzsxgmflzl_flzlForm_bqkce5)>(zzsxgmflzl_flzlForm_qcye5)+(zzsxgmflzl_flzlForm_bqfse5)|| (zzsxgmflzl_flzlForm_bqkce5)>(zzsxgmflzl_flzlForm_ysfwxsqbhssr5)",
						"targetName": "zzsxgmflzl_flzlForm_bqkce5",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010034,
						"code": "BDA0610611_10034",
						"vatTaxPayer": 2000010002,
						"message": "第12栏[期末余额]应等于第9栏[期初余额]+第10栏[本期发生额]-第11栏[本期扣除额]",
						"formula": "(zzsxgmflzl_flzlForm_qmye5)!=(zzsxgmflzl_flzlForm_qcye5)+(zzsxgmflzl_flzlForm_bqfse5)-(zzsxgmflzl_flzlForm_bqkce5)",
						"targetName": "zzsxgmflzl_flzlForm_qmye5",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010035,
						"code": "BDA0610611_10035",
						"vatTaxPayer": 2000010002,
						"message": "第14栏[本期扣除额]应=第11栏[本期扣除额]",
						"formula": "(zzsxgmflzl_flzlForm_ysfwxsbqkce5)!=(zzsxgmflzl_flzlForm_bqkce5)",
						"targetName": "zzsxgmflzl_flzlForm_ysfwxsbqkce5",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010036,
						"code": "BDA0610611_10036",
						"vatTaxPayer": 2000010002,
						"message": "第15栏[含税销售额]应等于第13栏[全部含税收入]-第14栏[本期扣除额]",
						"formula": "(zzsxgmflzl_flzlForm_ysfwxshsxse5)!=(zzsxgmflzl_flzlForm_ysfwxsqbhssr5)-(zzsxgmflzl_flzlForm_ysfwxsbqkce5)",
						"targetName": "zzsxgmflzl_flzlForm_ysfwxshsxse5",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010038,
						"code": "BDA0610611_10038",
						"vatTaxPayer": 2000010002,
						"message": "第16栏[货物及劳务]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynsejze)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynsejze",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010039,
						"code": "BDA0610611_10039",
						"vatTaxPayer": 2000010002,
						"message": "未达起征点且未代开增值税专用发票，不能填报第1栏第2列",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse)==0&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)!=0&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)<=30000*(qtxx_ssqkdys)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010040,
						"code": "BDA0610611_10040",
						"message": "[服务、不动产和无形资产]不能为负！",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010041,
						"code": "BDA0610611_10041",
						"vatTaxPayer": 2000010002,
						"message": "第2列第1栏应大于等于第2栏+第3栏之和 ",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)<((zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse))",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010042,
						"code": "BDA0610611_10042",
						"vatTaxPayer": 2000010002,
						"message": "您存在税务机关代开的增值税专用发票不含税销售额，当期服务、不动产和无形资产总[应征增值税不含税销售额]（含代开发票销售额）在起征点以下，应将第2行2列[税务机关代开的增值税专用发票不含税销售额]填至第1栏2列，剩余符合未超过免征条件的销售额填写至小微企业免税或未达起征点销售额[服务、不动产和无形资产_本期数]栏次",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)<=30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)!=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010043,
						"code": "BDA0610611_10043",
						"vatTaxPayer": 2000010002,
						"message": "未达到起征点，不能填报第3栏第2列",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)<=30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse)!=0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010045,
						"code": "BDA0610611_10045",
						"vatTaxPayer": 2000010002,
						"message": "未达起征点且未代开增值税专用发票，不能填报第4栏第2列",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)<=30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)!=0 && (zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse1)==0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010046,
						"code": "BDA0610611_10046",
						"vatTaxPayer": 2000010002,
						"message": "第4栏第2列应大于等于第5栏+第6栏之和 ",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)<(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse1)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse2)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse1,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse2",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010047,
						"code": "BDA0610611_10047",
						"vatTaxPayer": 2000010002,
						"message": "您存在税务机关代开的增值税专用发票不含税销售额，当期服务、不动产和无形资产总[应征增值税不含税销售额]（含代开发票销售额）在起征点以下，应将第5行2列[税务机关代开的增值税专用发票不含税销售额]填至第4栏2列，剩余符合未超过免征条件的销售额填写至小微企业免税或未达起征点销售额[服务、不动产和无形资产_本期数]栏次",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)<=30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)!=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse1)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_swjgdkdzzszyfpbhsxse1",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010048,
						"code": "BDA0610611_10048",
						"vatTaxPayer": 2000010002,
						"message": "未达到起征点，不能填报第6栏第2列",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)<=30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse2)!=0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpbhsxse2",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010049,
						"code": "BDA0610611_10049",
						"vatTaxPayer": 2000010002,
						"message": "[服务、不动产和无形资产]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010050,
						"code": "BDA0610611_10050",
						"vatTaxPayer": 2000010002,
						"message": "已达起征点，不能填报第10栏第2列[小微企业免税销售额]",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)>30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse)!=0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010051,
						"code": "BDA0610611_10051",
						"vatTaxPayer": 2000010002,
						"message": "[服务、不动产和无形资产]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010052,
						"code": "BDA0610611_10052",
						"vatTaxPayer": 2000010002,
						"message": "第10行第2列【数值】与第11行第2列【数值】不能同时大于0",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse)>0 && (zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse)>0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010053,
						"code": "BDA0610611_10053",
						"vatTaxPayer": 2000010002,
						"message": "[服务、不动产和无形资产]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010054,
						"code": "BDA0610611_10054",
						"vatTaxPayer": 2000010002,
						"message": "已达起征点，不能填报第11栏第2列[未达起征点销售额]",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xsczbdcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)>30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse)!=0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010055,
						"code": "BDA0610611_10055",
						"vatTaxPayer": 2000010002,
						"message": "[服务、不动产和无形资产]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_qtmsxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_qtmsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010056,
						"code": "BDA0610611_10056",
						"vatTaxPayer": 2000010002,
						"message": "[服务、不动产和无形资产]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010057,
						"code": "BDA0610611_10057",
						"vatTaxPayer": 2000010002,
						"message": "第13栏第2列[服务、不动产和无形资产]应大于或等于第14栏",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse)<(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpxse1)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_ckmsxse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpxse1",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010058,
						"code": "BDA0610611_10058",
						"vatTaxPayer": 2000010002,
						"message": "[服务、不动产和无形资产]不能为负！",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpxse1)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_skqjkjdptfpxse1",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010059,
						"code": "BDA0610611_10059",
						"vatTaxPayer": 2000010002,
						"message": "[服务、不动产和无形资产]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynsejze)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynsejze",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010060,
						"code": "BDA0610611_10060",
						"vatTaxPayer": 2000010002,
						"message": "第17行第2列应小于等于第9行第2列*0.05",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqmse)>((zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)*0.05)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqmse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010061,
						"code": "BDA0610611_10061",
						"vatTaxPayer": 2000010002,
						"message": "第17行第2列应大于等于第9行第2列*0.03",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqmse)<((zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_msxse)*0.03)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqmse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010062,
						"code": "BDA0610611_10062",
						"vatTaxPayer": 2000010002,
						"message": "第18栏第2列[小微企业免税额]应大于或者等于第10栏[小微企业免税销售额]*3%并且小于或者等于等于第10栏[小微企业免税销售额]*5%",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymse)<((zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse)*0.03)||(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymse)>((zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymsxse)*0.05)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010063,
						"code": "BDA0610611_10063",
						"vatTaxPayer": 2000010002,
						"message": "第19栏第2列[未达起征点免税额]应大于或者等于第11栏[未达起征点销售额]*0.03并且小于或者等于等于第11栏[未达起征点销售额]*0.05",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdmse)<((zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse)*0.03)||(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdmse)>((zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdxse)*0.05)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdmse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010064,
						"code": "BDA0610611_10064",
						"vatTaxPayer": 2000010002,
						"message": "[服务、不动产和无形资产]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqyjse1)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqyjse1",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010065,
						"code": "BDA0610611_10065",
						"vatTaxPayer": 2000010002,
						"message": "当逾期未认定的一般纳税人标志不为Y，且第2行第1列【数值】等于0时 ,且第1行第1列【数值】+第7行第1列【数值】大于0时，第1行第1列【数值】+第7行第1列【数值】+第9行第1列【数值】+第13行第1列【数值】应大于起征点",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_swjgdkdzzszyfpbhsxse)==0&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)>0&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)<=30000*(qtxx_ssqkdys)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010066,
						"code": "BDA0610611_10066",
						"vatTaxPayer": 2000010002,
						"message": "第2列[本期发生额]不为0，请据实填写第5列[全部含税收入]！",
						"formula": "(zzsxgmflzl_flzlForm_bqfse) !=0 && (zzsxgmflzl_flzlForm_ysfwxsqbhssr) ==0",
						"targetName": "zzsxgmflzl_flzlForm_ysfwxsqbhssr",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010067,
						"code": "BDA0610611_10067",
						"vatTaxPayer": 2000010002,
						"message": "主表第16栏第1列[货物及劳务]+第2列[服务、不动产和无形资产]应等于附表《增值减免税申报明细表》[本期实际抵减税额]的合计",
						"formula": "(zzsjmssbmxb_zzsjmssbmxbjsxmGrid_zzsjmssbmxbjsxmGridlbVO_0_bqsjdjse)!=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynsejze)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynsejze)",
						"targetName": "zzsjmssbmxb_zzsjmssbmxbjsxmGrid_zzsjmssbmxbjsxmGridlbVO_0_bqsjdjse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010069,
						"code": "BDA0610611_10069",
						"vatTaxPayer": 2000010002,
						"message": "[货物及劳务]不能为负",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymsxse)<0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010070,
						"code": "BDA0610611_10070",
						"vatTaxPayer": 2000010002,
						"message": "应税行为（3%征收率）扣除额计算本期发生额不能为负",
						"formula": "(zzsxgmflzl_flzlForm_bqfse)<0",
						"targetName": "zzsxgmflzl_flzlForm_bqfse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010071,
						"code": "BDA0610611_10071",
						"vatTaxPayer": 2000010002,
						"message": "应税行为（3%征收率）扣除额计算本期扣除额不能为负",
						"formula": "(zzsxgmflzl_flzlForm_bqkce)<0",
						"targetName": "zzsxgmflzl_flzlForm_bqkce",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010072,
						"code": "BDA0610611_10072",
						"vatTaxPayer": 2000010002,
						"message": "应税行为（3%征收率）扣除额计算全部含税收入（适用3%征收率）不能为负",
						"formula": "(zzsxgmflzl_flzlForm_ysfwxsqbhssr)<0",
						"targetName": "zzsxgmflzl_flzlForm_ysfwxsqbhssr",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010073,
						"code": "BDA0610611_10073",
						"vatTaxPayer": 2000010002,
						"message": "应税行为（5%征收率）扣除额计算本期发生额不能为负",
						"formula": "(zzsxgmflzl_flzlForm_bqfse5)<0",
						"targetName": "zzsxgmflzl_flzlForm_bqfse5",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010074,
						"code": "BDA0610611_10074",
						"vatTaxPayer": 2000010002,
						"message": "应税行为（5%征收率）扣除额计算本期扣除额不能为负",
						"formula": "(zzsxgmflzl_flzlForm_bqkce5)<0",
						"targetName": "zzsxgmflzl_flzlForm_bqkce5",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010075,
						"code": "BDA0610611_10075",
						"vatTaxPayer": 2000010002,
						"message": "应税行为（5%征收率）扣除额计算全部含税收入（适用5%征收率）不能为负",
						"formula": "(zzsxgmflzl_flzlForm_ysfwxsqbhssr5)<0",
						"targetName": "zzsxgmflzl_flzlForm_ysfwxsqbhssr5",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010076,
						"code": "BDA0610611_10076",
						"vatTaxPayer": 2000010002,
						"message": "第16行第1列应小于等于第15行第1列",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynse)<(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynsejze)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_bqynsejze",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010077,
						"code": "BDA0610611_10077",
						"vatTaxPayer": 2000010002,
						"message": "第16行第2列应小于等于第15行第2列",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynse)<(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynsejze)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_bqynsejze",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010079,
						"code": "BDA0610611_10079",
						"vatTaxPayer": 2000010002,
						"message": "当逾期未认定的一般纳税人标志不为Y时，第10行第1列【数值】应小于等于起征点金额",
						"formula": "qtxx_yqwrdzzsybnsrBz!='Y'?(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymsxse)>30000*(qtxx_ssqkdys):false",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010080,
						"code": "BDA0610611_10080",
						"vatTaxPayer": 2000010002,
						"message": "您存在税务机关代开的增值税专用发票不含税销售额，当期货物及劳务总[应征增值税不含税销售额]（含代开发票销售额）【数值】在起征点以下，应将第2行1列[税务机关代开的增值税专用发票不含税销售额]【数值】填至第1栏1列，剩余符合未超过免征条件的销售额填写至小微企业免税或未达起征点销售额[货物及劳务_本期数]栏次",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)<=30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)!=(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_swjgdkdzzszyfpbhsxse)",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010081,
						"code": "BDA0610611_10081",
						"vatTaxPayer": 2000010002,
						"message": "已达起征点，不能填报第10栏第1列[小微企业免税销售额]",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)>30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymsxse)!=0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xwqymsxse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010082,
						"code": "BDA0610611_10082",
						"vatTaxPayer": 2000010002,
						"message": "主表未达起征点且未代开增值税专用发票，不能填报第1栏第1列",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_xssygdysgdzcbhsxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_msxse)+(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_ckmsxse)<=30000*(qtxx_ssqkdys)&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse)!=0&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_swjgdkdzzszyfpbhsxse)==0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_0_yzzzsbhsxse",
						"YZPZZLDM": "BDA0610611"
					},
					{
						"id": 100010083,
						"code": "BDA0610611_10083",
						"message": "第18行第2列与第19行第2列不能同时大于0",
						"formula": "(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymse)>0&&(zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdmse)>0",
						"targetName": "zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_xwqymse,zzssyyxgmnsr_zzsxgmGrid_zzsxgmGridlb_1_wdqzdmse",
						"taxProjectId": "1001",
						"YZPZZLDM": "BDA0610611"
					}
				],
				"mapRelation": {
					"tTableMapping": {
						"zzssyyxgmnsr": "col"
					},
					"zzssyyxgmnsr": {
						"yzzzsbhsxse": 1,
						"swjgdkdzzszyfpbhsxse": 2,
						"skqjkjdptfpbhsxse": 3,
						"xsczbdcbhsxse": 4,
						"swjgdkdzzszyfpbhsxse1": 5,
						"skqjkjdptfpbhsxse2": 6,
						"xssygdysgdzcbhsxse": 7,
						"skqjkjdptfpbhsxse1": 8,
						"msxse": 9,
						"xwqymsxse": 10,
						"wdqzdxse": 11,
						"qtmsxse": 12,
						"ckmsxse": 13,
						"skqjkjdptfpxse1": 14,
						"bqynse": 15,
						"bqynsejze": 16,
						"bqmse": 17,
						"xwqymse": 18,
						"wdqzdmse": 19,
						"ynsehj": 20,
						"bqyjse1": 21,
						"bqybtse": 22,
					},
					"zzssyyybnsrzb": {
						"mshwxse": 9,
						"sqldse": 13,
						"yshwxse": 2,
						"ckkjzyjksyjse": 29,
						"asysljsxse": 1,
						"ydksehj": 17,
						"ynsejze": 23,
						"bqjnqjse": 31,
						"jzjtsjtse": 35,
						"qcwjse": 25,
						"qmwjse": 32,
						"jybfYnse": 21,
						"qmwjseQjse": 33,
						"msxse": 8,
						"jxse": 12,
						"qcwjcbse": 36,
						"mslwxse": 10,
						"ynsehj": 24,
						"bqrkcbse": 37,
						"bqyjse": 27,
						"fcyjse": 28,
						"jybfNsjctzxse": 6,
						"mdtbfckxse": 7,
						"ynse": 19,
						"qmldse": 20,
						"qmwjcbse": 38,
						"jybfNsjcybjse": 22,
						"bqybtse": 34,
						"xxse": 11,
						"syslNsjctzxse": 4,
						"mdtytse": 15,
						"syslNsjcybjse": 16,
						"sjdkse": 18,
						"bqjnsqynse": 30,
						"ssckkjzyjkstse": 26,
						"ajybfjsxse": 5,
						"jxsezc": 14,
						"yslwxse": 3
					},
					"tYBTableMapping": {
						"zzssyyybnsrzb": "col"
					}
				},
				"zzssyyxgmnsrySbSbbdxxVO": {
					"isInit": false,
					"isCanModify": false,
					"qtxx": {
						"ssqkdys": 3,
						"myqzd": 100000,
						"yqsbBz": "Y",
						"yqsbMes": "该纳税人本属期逾期申报（逾期天数31）",
						"zzsqzd": "90000.03",
						"zzsysfwqzd": "0.0",
						"yshwlwBz": "Y",
						"ysfwBz": "N",
						"yshwlwFpdkbhsxse": "50912.63",
						"ysfwFpdkbhsxse": "0.0",
						"ysfwFpdkbhsxse5": "0.0",
						"dqdeBz": "N",
						"dqdeYshwlwHdxse": "0.0",
						"dqdeYsfwHdxse": "0.0",
						"dqdeYshwlwHdynse": "0.0",
						"dqdeYsfwHdynse": "0.0",
						"zfjgBz": "2",
						"yzl": "0.0",
						"desl1": "0.0",
						"fgdqyBz": "N",
						"fzjgfgdqyse": "0.0",
						"ysfwydbyhyyjse": "0.0",
						"hwlwydbyhyyjse": "0.0",
						"flzlqcye": "0.0",
						"flzlqcye5": "0.0",
						"qmsezzsskxtfy5": "0.0",
						"qmsefzjgyzjnsk5": "0.0",
						"qmsejzfwyzjnsk5": "0.0",
						"qmsexsbdcyzjnsk5": "0.0",
						"qmseczbdcyzjnsk5": "0.0",
						"yqwrdzzsybnsrBz": "N",
						"ptfpsjkpje": "0.0",
						"zpje": "50912.63",
						"ppje": "0.0",
						"iswkjfpsqd": "N",
						"fqmsqBz": "Y",
						"zgslhl": "0.0",
						"zgslfw": "0.0",
						"acsbxseHj": "0.0",
						"acsbfwxseHj": "0.0",
						"bsrxm": "李正青",
						"cwfzrxm": "李明琦",
						"fddbrxm": "徐永波",
						"bsrlxdh": "18085018512"
					},
					"zzssyyxgmnsr": {
						"sbbhead": {
							"nsrsbh": "91520123565011970A",
							"nsrmc": "贵州省修文县兴筑建材有限责任公司",
							"skssqq": "2018-10-01",
							"skssqz": "2018-12-31",
							"sbsxDm1": "11",
							"sbrq1": "2019-02-15",
							"YZPZZLDM": "BDA0610611"
						},
						"zzsxgmGrid": {
							"zzsxgmGridlb": [
								{
									"ewblxh": "1",
									"yzzzsbhsxse": "50912.63",
									"swjgdkdzzszyfpbhsxse": "50912.63",
									"skqjkjdptfpbhsxse": "0.00",
									"xsczbdcbhsxse": "- -",
									"swjgdkdzzszyfpbhsxse1": "- -",
									"skqjkjdptfpbhsxse2": "- -",
									"xssygdysgdzcbhsxse": "0.00",
									"skqjkjdptfpbhsxse1": "0.00",
									"msxse": "0.00",
									"xwqymsxse": "0.00",
									"wdqzdxse": "0.00",
									"qtmsxse": "0.00",
									"ckmsxse": "0.00",
									"skqjkjdptfpxse1": "0.00",
									"hdxse": "0.00",
									"bqynse": "1527.38",
									"hdynse": "0.00",
									"bqynsejze": "0.00",
									"bqmse": "0.00",
									"xwqymse": "0.00",
									"wdqzdmse": "0.00",
									"ynsehj": "1527.38",
									"bqyjse1": "0.00",
									"bqybtse": "1527.38"
								},
								{
									"ewblxh": "2",
									"yzzzsbhsxse": "0.00",
									"swjgdkdzzszyfpbhsxse": "0.00",
									"skqjkjdptfpbhsxse": "0.00",
									"xsczbdcbhsxse": "0.00",
									"swjgdkdzzszyfpbhsxse1": "0.00",
									"skqjkjdptfpbhsxse2": "0.00",
									"xssygdysgdzcbhsxse": "- -",
									"skqjkjdptfpbhsxse1": "- -",
									"msxse": "0.00",
									"xwqymsxse": "0.00",
									"wdqzdxse": "0.00",
									"qtmsxse": "0.00",
									"ckmsxse": "0.00",
									"skqjkjdptfpxse1": "0.00",
									"hdxse": "0.00",
									"bqynse": "0.00",
									"hdynse": "0.00",
									"bqynsejze": "0.00",
									"bqmse": "0.00",
									"xwqymse": "0.00",
									"wdqzdmse": "0.00",
									"ynsehj": "0.00",
									"bqyjse1": "0.00",
									"bqybtse": "0.00"
								},
								{
									"ewblxh": "3",
									"yzzzsbhsxse": "656747.59",
									"swjgdkdzzszyfpbhsxse": "645097.10",
									"skqjkjdptfpbhsxse": "11650.49",
									"xsczbdcbhsxse": "0.00",
									"swjgdkdzzszyfpbhsxse1": "0.00",
									"skqjkjdptfpbhsxse2": "0.00",
									"xssygdysgdzcbhsxse": "0.00",
									"skqjkjdptfpbhsxse1": "0.00",
									"msxse": "0.00",
									"xwqymsxse": "0.00",
									"wdqzdxse": "0.00",
									"qtmsxse": "0.00",
									"ckmsxse": "0.00",
									"skqjkjdptfpxse1": "0.00",
									"hdxse": "0.00",
									"bqynse": "19702.43",
									"hdynse": "0.00",
									"bqynsejze": "0.00",
									"bqmse": "0.00",
									"xwqymse": "0.00",
									"wdqzdmse": "0.00",
									"ynsehj": "19702.43",
									"bqyjse1": "0.00",
									"bqybtse": "13527.38"
								},
								{
									"ewblxh": "4",
									"yzzzsbhsxse": "0.00",
									"swjgdkdzzszyfpbhsxse": "0.00",
									"skqjkjdptfpbhsxse": "0.00",
									"xsczbdcbhsxse": "0.00",
									"swjgdkdzzszyfpbhsxse1": "0.00",
									"skqjkjdptfpbhsxse2": "0.00",
									"xssygdysgdzcbhsxse": "0.00",
									"skqjkjdptfpbhsxse1": "0.00",
									"msxse": "0.00",
									"xwqymsxse": "0.00",
									"wdqzdxse": "0.00",
									"qtmsxse": "0.00",
									"ckmsxse": "0.00",
									"skqjkjdptfpxse1": "0.00",
									"hdxse": "0.00",
									"bqynse": "0.00",
									"hdynse": "0.00",
									"bqynsejze": "0.00",
									"bqmse": "0.00",
									"xwqymse": "0.00",
									"wdqzdmse": "0.00",
									"ynsehj": "0.00",
									"bqyjse1": "0.00",
									"bqybtse": "0.00"
								}
							]
						},
						"slxxForm": {
							"sfzxsb": "Y",
							"bsrxm": "李正青",
							"cwfzrxm": "李明琦",
							"fddbrxm": "徐永波",
							"bsrlxdh": "18085018512",
							"slswjgDm": "15201236300"
						}
					},
					"zzsxgmflzl": {
						"flzlForm": {
							"qcye": "0.00",
							"bqfse": "0.00",
							"bqkce": "0.00",
							"qmye": "0.00",
							"ysfwxsqbhssr": "0.00",
							"ysfwxsbqkce": "0.00",
							"ysfwxshsxse": "0.00",
							"ysfwxsbhsxse": "0.00",
							"qcye5": "0.00",
							"bqfse5": "0.00",
							"bqkce5": "0.00",
							"qmye5": "0.00",
							"ysfwxsqbhssr5": "0.00",
							"ysfwxsbqkce5": "0.00",
							"ysfwxshsxse5": "0.00",
							"ysfwxsbhsxse5": "0.00"
						}
					},
					"zzsjmssbmxb": {
						"zzsjmssbmxbjsxmGrid": {
							"zzsjmssbmxbjsxmGridlbVO": [
								{
									"ewbhxh": "1",
									"hmc": "合计",
									"swsxDm": "",
									"qcye": "0.00",
									"bqfse": "0.00",
									"bqydjse": "0.00",
									"bqsjdjse": "0.00",
									"qmye": "0.00"
								}
							]
						},
						"zzsjmssbmxbmsxmGrid": {
							"zzsjmssbmxbmsxmGridlbVO": [
								{
									"ewbhxh": "1",
									"hmc": "合计",
									"swsxDm": "",
									"mzzzsxmxse": "0.00",
									"bqsjkcje": "0.00",
									"kchmsxse": "0.00",
									"msxsedyjxse": "0.00",
									"mse": "0.00"
								},
								{
									"ewbhxh": "2",
									"hmc": "出口免税",
									"swsxDm": "",
									"mzzzsxmxse": "0.00",
									"bqsjkcje": "- -",
									"kchmsxse": "- -",
									"msxsedyjxse": "- -",
									"mse": "- -"
								},
								{
									"ewbhxh": "3",
									"hmc": "其中：跨境服务",
									"swsxDm": "",
									"mzzzsxmxse": "0.00",
									"bqsjkcje": "- -",
									"kchmsxse": "- -",
									"msxsedyjxse": "- -",
									"mse": "- -"
								}
							]
						}
					},
					"zzsxgmkcxmqd": {
						"zgswjgdm": "",
						"zgswjgmc": "国家税务总局修文县税务局",
						"nssbrq": "2019-02-15",
						"skssq": "2018-10-01|2018-12-31",
						"sdrq": "20190215",
						"jsr": "网上报税系统",
						"zgswjggz": "国家税务总局修文县税务局",
						"djxh": "10115201000083642834",
						"ssqq": "2018-10-01",
						"ssqz": "2018-12-31",
						"yxbz": "Y",
						"kcxmqdmx": [
							{
								"pzzl": "合计",
								"kpfnsrsbh": "- -",
								"kpfdwmc": "- -",
								"fpdm": "- -",
								"fphm": "- -",
								"fwxmmc": "- -",
								"yxkcxmje": "0.00",
								"kjrq": "- -"
							}
						]
					},
					"zzsxgmxsbdcqkb": {
						"djxh": "10115201000083642834",
						"nsrsbh": "91520123565011970A",
						"nsrmc": "贵州省修文县兴筑建材有限责任公司",
						"zgswjggz": "国家税务总局修文县税务局",
						"tbrq": "2019-02-15",
						"sdrq": "20190215",
						"jsr": "网上报税系统",
						"xsbdcbhsxse": "0.00",
						"ssqq": "2018-10-01",
						"ssqz": "2018-12-31"
					},
					"zzsxgmfjssb": {
						"xgmfjsxxGrid": {
							"xgmfjsxxGridlb": [
								{
									"sybh": "",
									"rdpzuuid": "",
									"zsxmDm": "10109",
									"zsxmDmMc": "城市维护建设税",
									"zspmDm": "101090201",
									"zspmDmMc": "县城、镇（增值税附征）",
									"jsyj": "1527.38",
									"sl1": "0.05",
									"ynse": "76.37",
									"ssjmxzDm": "",
									"ssjmxzDmMc": "其他",
									"jmse": "76.37",
									"yjse1": "0.00",
									"ybtse": "0.00",
									"rdyxqq": "",
									"rdyxqz": ""
								},
								{
									"sybh": "",
									"rdpzuuid": "",
									"zsxmDm": "30203",
									"zsxmDmMc": "教育费附加",
									"zspmDm": "302030100",
									"zspmDmMc": "增值税教育费附加",
									"jsyj": "1527.38",
									"sl1": "0.03",
									"ynse": "45.82",
									"ssjmxzDm": "0061129999",
									"ssjmxzDmMc": "其他",
									"jmse": "45.82",
									"yjse1": "0.00",
									"ybtse": "0.00",
									"rdyxqq": "",
									"rdyxqz": ""
								},
								{
									"sybh": "",
									"rdpzuuid": "",
									"zsxmDm": "30216",
									"zsxmDmMc": "地方教育附加",
									"zspmDm": "302160100",
									"zspmDmMc": "增值税地方教育附加",
									"jsyj": "1527.38",
									"sl1": "0.02",
									"ynse": "30.55",
									"ssjmxzDm": "0099129999",
									"ssjmxzDmMc": "其他",
									"jmse": "30.55",
									"yjse1": "0.00",
									"ybtse": "0.00",
									"rdyxqq": "",
									"rdyxqz": ""
								}
							]
						}
					}
				}
			}

		},
		openingZZSInit: (option) => fetch.post('/v1/tax/zzssb/common/openingZZSInit', option),
		autoCreate: (option) => fetch.post('/v1/tax/zzssb/common/autoCreate', option),
		queryReport: (option) => {
			return {
				"result": true, "value": { "haveSelected": false, "reportList": [{ "projectReportCode": "BDA0610606", "projectReportName": "《增值税纳税申报表（适用于增值税一般纳税人）》", "canDel": true, "selected": false, "bstj": "", "rowNo": 1 }, { "projectReportCode": "BDA0610339", "projectReportName": "《增值税纳税申报表附列资料（表一）（本期销售情况明细）》", "canDel": true, "selected": false, "bstj": "", "rowNo": 2 }, { "projectReportCode": "BDA0610337", "projectReportName": "《增值税纳税申报表附列资料（表二）（本期进项税额明细）》", "canDel": true, "selected": false, "bstj": "", "rowNo": 3 }, { "projectReportCode": "BDA0610338", "projectReportName": "《增值税纳税申报表附列资料（表三）（服务、不动产和无形资产扣除项目明细）》", "canDel": true, "selected": false, "bstj": "", "rowNo": 4 }, { "projectReportCode": "BDA0610566", "projectReportName": "《增值税纳税申报表附列资料（表四）（税额抵减情况表）》", "canDel": true, "selected": false, "bstj": "", "rowNo": 5 }, { "projectReportCode": "BDAbdcfqdkjsb", "projectReportName": "《增值税纳税申报表附列资料（五）（不动产分期抵扣计算表）》", "canDel": true, "selected": false, "bstj": "", "rowNo": 6 }, { "projectReportCode": "BDA0610758", "projectReportName": "《增值税减免税申报明细表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 7 }, { "projectReportCode": "BDAygzsffxcsmxb", "projectReportName": "《营改增税负分析测算明细表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 8 }, { "projectReportCode": "FWBDCHWXZCKCXMQD", "projectReportName": "《服务、不动产和无形资产扣除项目清单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 9 }, { "projectReportCode": "YBNSRZZS_BCSBB", "projectReportName": "《增值税补充申报表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 10 }, { "projectReportCode": "BDA0610113", "projectReportName": "《成品油购销存情况明细表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 11 }, { "projectReportCode": "BDA0610112", "projectReportName": "《成品油购销存数量明细表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 12 }, { "projectReportCode": "BDA0610568", "projectReportName": "《加油站月销售油品汇总表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 13 }, { "projectReportCode": "BDA0610564", "projectReportName": "《加油站月份加油信息明细表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 14 }, { "projectReportCode": "BDA0610028", "projectReportName": "《机动车辆生产企业销售明细表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 15 }, { "projectReportCode": "BDA0610027", "projectReportName": "《机动车辆生产企业销售情况统计表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 16 }, { "projectReportCode": "BDA0610026", "projectReportName": "《机动车销售统一发票领用存月报表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 17 }, { "projectReportCode": "BDA0610025", "projectReportName": "《机动车销售统一发票清单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 18 }, { "projectReportCode": "BDA0610029", "projectReportName": "《机动车辆经销企业销售明细表", "canDel": true, "selected": false, "bstj": "", "rowNo": 19 }, { "projectReportCode": "BDA0610492", "projectReportName": "《增值税运输发票抵扣清单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 20 }, { "projectReportCode": "BDA0210112", "projectReportName": "《海关完税凭证抵扣联数据采集表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 21 }, { "projectReportCode": "BDA0610569", "projectReportName": "《代扣代缴税收通用缴款书抵扣清单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 22 }, { "projectReportCode": "BDA0610614", "projectReportName": "《汇总纳税企业通用传递单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 23 }, { "projectReportCode": "BDA0610669", "projectReportName": "《汇总纳税企业增值税分配表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 24 }, { "projectReportCode": "BDA0610507", "projectReportName": "《农产品核定扣除增值税进项税额计算表（汇总表）》", "canDel": true, "selected": false, "bstj": "", "rowNo": 25 }, { "projectReportCode": "BDA0610534", "projectReportName": "《投入产出法核定农产品增值税进项税额计算表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 26 }, { "projectReportCode": "BDA0610491", "projectReportName": "《成本法核定农产品增值税进项税额计算表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 27 }, { "projectReportCode": "BDA0610506", "projectReportName": "《购进农产品直接销售核定农产品增值税进项税额计算表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 28 }, { "projectReportCode": "BDA0610505", "projectReportName": "《购进农产品用于生产经营且不构成货物实体核定农产品增值税进项税额计算表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 29 }, { "projectReportCode": "BDA0610535", "projectReportName": "《电力企业增值税销项税额和进项税额传递单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 30 }, { "projectReportCode": "BDA0610670", "projectReportName": "《增值税税款分解表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 31 }, { "projectReportCode": "BDA0610630", "projectReportName": "《邮政企业分支机构增值税汇总纳税信息传递单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 32 }, { "projectReportCode": "BDA0610631", "projectReportName": "《铁路运输企业分支机构增值税汇总纳税信息传递单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 33 }, { "projectReportCode": "BDA0610863", "projectReportName": " 《铁路建设基金纳税申报表》  ", "canDel": true, "selected": false, "bstj": "", "rowNo": 34 }, { "projectReportCode": "BDA0610667", "projectReportName": "《电信企业分支机构增值税汇总纳税信息传递单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 35 }, { "projectReportCode": "BDA0610628", "projectReportName": "《航空运输企业分支机构传递单》", "canDel": true, "selected": false, "bstj": "", "rowNo": 36 }, { "projectReportCode": "BDA0610700", "projectReportName": "《增值税一般纳税人本期应纳税额按预算科目分解表》", "canDel": true, "selected": false, "bstj": "", "rowNo": 37 }, { "projectReportCode": "YBNSRZZS_FJSSB", "projectReportName": "《附加税（费）申报信息》", "canDel": true, "selected": false, "bstj": "", "rowNo": 38 }] }
			}
		},
		findById: (option) => fetch.post('/v1/tax/sb/appraisal/findById', option),
		generatePDF: (option, parentNode, cb) => fetch.pdfPost('/v1/tax/zzssb/pdf/generatePDF', option, undefined, parentNode, cb),
		generateImportPDF: (option) => fetch.formPost('/v1/tax/zzssb/pdf/download', option),
		downXMl: (option) => fetch.formPost('/v1/tax/reportData/downXMl', option),	//导出XML报盘	        
		fjsAutoLsb: (option) => fetch.post('/v1/tax/zzssb/additional/fjsAutoLsb', option),	//
		query: (option) => fetch.post('/v1/appsource/query', option),	//

	}
}